# Generated by Django 4.2.21 on 2025-06-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawmakerVoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('agree_count', models.PositiveIntegerField(default=0)),
                ('oppose_count', models.PositiveIntegerField(default=0)),
                ('invalid_or_abstain_count', models.PositiveIntegerField(default=0)),
                ('agree_and_passed', models.PositiveIntegerField(default=0)),
                ('oppose_and_failed', models.PositiveIntegerField(default=0)),
                ('agree_and_failed', models.PositiveIntegerField(default=0)),
                ('oppose_and_passed', models.PositiveIntegerField(default=0)),
                ('lawmaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.lawmaker')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_result', models.CharField(choices=[('agree', '찬성'), ('oppose', '반대'), ('abstain', '기권'), ('absent', '불참')], max_length=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.billid')),
                ('lawmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.lawmaker')),
            ],
            options={
                'unique_together': {('lawmaker', 'bill')},
            },
        ),
    ]
