# Generated by Django 4.2.21 on 2025-06-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0001_initial'),
        ('vote', '0002_billvotebyparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawmaker',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislation.member'),
        ),
    ]
