# Generated by Django 4.2.21 on 2025-06-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_lawmaker_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billvotebyparty',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.billid'),
        ),
    ]
