# Generated by Django 4.2.21 on 2025-06-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_billvotebyparty_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillVoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('participation_rate', models.FloatField(default=0.0)),
                ('agree_count', models.PositiveIntegerField(default=0)),
                ('oppose_count', models.PositiveIntegerField(default=0)),
                ('abstain_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.billid')),
            ],
        ),
    ]
