# Generated by Django 4.2.21 on 2025-06-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('total_meetings', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('absences', models.IntegerField()),
                ('leaves', models.IntegerField()),
                ('business_trips', models.IntegerField()),
                ('attendance_rate', models.FloatField()),
                ('absence_rate', models.FloatField()),
            ],
        ),
    ]
