# Generated by Django 4.2.21 on 2025-06-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100, unique=True)),
                ('avg_attendance', models.FloatField(default=0.0)),
                ('max_attendance', models.FloatField(default=0.0)),
                ('min_attendance', models.FloatField(default=0.0)),
                ('std_attendance', models.FloatField(default=0.0)),
                ('avg_invalid_vote_ratio', models.FloatField(default=0.0)),
                ('max_invalid_vote_ratio', models.FloatField(default=0.0)),
                ('min_invalid_vote_ratio', models.FloatField(default=0.0)),
                ('std_invalid_vote_ratio', models.FloatField(default=0.0)),
                ('avg_vote_match_ratio', models.FloatField(default=0.0)),
                ('max_vote_match_ratio', models.FloatField(default=0.0)),
                ('min_vote_match_ratio', models.FloatField(default=0.0)),
                ('std_vote_match_ratio', models.FloatField(default=0.0)),
                ('avg_vote_mismatch_ratio', models.FloatField(default=0.0)),
                ('max_vote_mismatch_ratio', models.FloatField(default=0.0)),
                ('min_vote_mismatch_ratio', models.FloatField(default=0.0)),
                ('std_vote_mismatch_ratio', models.FloatField(default=0.0)),
                ('bill_pass_sum', models.IntegerField(default=0)),
                ('petition_sum', models.IntegerField(default=0)),
                ('petition_pass_sum', models.IntegerField(default=0)),
                ('committee_leader_count', models.IntegerField(default=0)),
                ('committee_secretary_count', models.IntegerField(default=0)),
                ('member_count', models.IntegerField(default=0)),
                ('weighted_score', models.FloatField(default=0.0)),
                ('avg_total_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100)),
                ('total_score', models.FloatField()),
                ('attendance_score', models.FloatField()),
                ('bill_pass_score', models.FloatField()),
                ('petition_score', models.IntegerField()),
                ('petition_result_score', models.IntegerField()),
                ('committee_score', models.IntegerField()),
                ('invalid_vote_ratio', models.FloatField()),
                ('vote_match_ratio', models.FloatField()),
                ('vote_mismatch_ratio', models.FloatField()),
                ('lawmaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.lawmaker')),
            ],
        ),
    ]
