# Generated by Django 4.2.21 on 2025-06-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='committee_leader_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='committee_leader_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='performance',
            name='committee_secretary_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='committee_secretary_score',
            field=models.FloatField(default=0.0),
        ),
    ]
