# Generated by Django 4.2.21 on 2025-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_performance_committee_leader_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyperformance',
            name='attendance_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partyperformance',
            name='bill_pass_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partyperformance',
            name='invalid_vote_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partyperformance',
            name='petition_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partyperformance',
            name='petition_result_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partyperformance',
            name='vote_match_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partyperformance',
            name='vote_mismatch_pct',
            field=models.FloatField(default=0.0),
        ),
    ]
