# Generated by Django 4.2.21 on 2025-06-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGE', models.CharField(max_length=10)),
                ('BILL_ID', models.CharField(max_length=50, unique=True)),
                ('BILL_NM', models.CharField(blank=True, max_length=200)),
                ('PROC_RESULT_CD', models.CharField(blank=True, max_length=20)),
                ('PROPOSER', models.CharField(blank=True, max_length=200)),
                ('DETAIL_LINK', models.URLField(blank=True)),
                ('RGS_PROC_DT', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BILL_ID', models.CharField(max_length=50, unique=True)),
                ('BILL_NM', models.CharField(blank=True, max_length=200)),
                ('MAIN_PROPOSER', models.CharField(default='UNKNOWN', max_length=100)),
                ('CO_PROPOSERS', models.TextField(default='[]')),
                ('PROC_RESULT', models.CharField(blank=True, default='UNKNOWN', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('approved', models.IntegerField(default=0)),
                ('discarded', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPT_NM', models.CharField(blank=True, max_length=100)),
                ('JOB_RES_NM', models.CharField(blank=True, max_length=100)),
                ('HG_NM', models.CharField(max_length=100)),
                ('POLY_NM', models.CharField(blank=True, max_length=100)),
                ('MONA_CD', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('BILL_ID', models.CharField(max_length=100, unique=True)),
                ('BILL_NM', models.CharField(blank=True, max_length=200)),
                ('PROC_RESULT_CD', models.CharField(blank=True, max_length=50)),
                ('DETAIL_LINK', models.URLField(blank=True)),
                ('RGS_PROC_DT', models.CharField(blank=True, max_length=20, null=True)),
                ('PROPOSER', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Costly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('BILL_ID', models.CharField(max_length=100, unique=True)),
                ('BILL_NM', models.CharField(blank=True, max_length=200)),
                ('PROC_RESULT_CD', models.CharField(blank=True, max_length=50)),
                ('DETAIL_LINK', models.URLField(blank=True)),
                ('RGS_PROC_DT', models.CharField(blank=True, max_length=20, null=True)),
                ('PROPOSER', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('BILL_ID', models.CharField(max_length=100, unique=True)),
                ('BILL_NM', models.CharField(blank=True, max_length=200)),
                ('PROC_RESULT_CD', models.CharField(blank=True, max_length=50)),
                ('DETAIL_LINK', models.URLField(blank=True)),
                ('RGS_PROC_DT', models.CharField(blank=True, max_length=20, null=True)),
                ('PROPOSER', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BILL_ID', models.CharField(max_length=100, unique=True)),
                ('BILL_NO', models.CharField(blank=True, max_length=50)),
                ('BILL_NM', models.TextField(blank=True)),
                ('PROPOSER', models.CharField(blank=True, max_length=100)),
                ('PROC_RESULT_CD', models.CharField(blank=True, max_length=50)),
                ('ANNOUNCE_DT', models.CharField(blank=True, max_length=20, null=True)),
                ('DETAIL_LINK', models.URLField(blank=True)),
                ('RGS_PROC_DT', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('mona_cd', models.CharField(max_length=20)),
                ('committees', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BILL_ID', models.CharField(max_length=50, unique=True)),
                ('BILL_NO', models.CharField(blank=True, max_length=50)),
                ('BILL_NAME', models.CharField(max_length=200)),
                ('PROPOSER', models.CharField(blank=True, max_length=200)),
                ('PROC_RESULT_CD', models.CharField(blank=True, max_length=50)),
                ('DETAIL_LINK', models.URLField(blank=True)),
                ('PROPOSE_DT', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=50, unique=True)),
                ('member_name', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetitionIntroducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introducer_name', models.CharField(blank=True, max_length=200)),
                ('petition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legislation.petition')),
            ],
        ),
    ]
